version: 2.1
setup: true

# define the parameters from the setup config. 
 parameters: 
   megalinter: 
     type: boolean 
     default: false 
   build-fedora-image: 
     type: boolean 
     default: false

orbs:
  path-filtering: circleci/path-filtering@1.1.0
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          # Examples: https://github.com/CircleCI-Public/dynamic-configuration-examples/tree/generate-config-file-main
          # base-revision: master
          base-revision: RelativeSure-patch-1
          config-path: .circleci/no-updates.yml
          resource_class: large
          tag: "3.9"
          mapping: |
           .* megalinter true .circleci/megalinter.yml
           docker/fedora/.* build-fedora-image true .circleci/fedora-actions.yml